sub-pos=95
no-osc
sub-font='07YasashisaAntique'
#sub-font='Monospace'  
sub-color='#BBBBBB'
sub-scale=1.65
sub-outline-color='#000000'
sub-outline-size=2
alang=ja,jpn,jap,jpa,eng,en
slang=ja,jpn,jap,jpa,eng,en
