sub-pos=95
no-osc
sub-font='07YasashisaAntique'
#sub-font='Monospace'  
sub-color='#BBBBBB'
sub-scale=1.65
sub-outline-color='#222222'
sub-outline-size=2
geometry=1080x920
alang=ja,jpn,jap,jpa,eng,en
slang=ja,jpn,jap,jpa,eng,en
